# Generated by Django 4.2.7 on 2025-10-10 07:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_monitoring_active', models.BooleanField(default=True)),
                ('global_check_interval', models.PositiveIntegerField(default=300, help_text='Global check interval in seconds')),
                ('max_concurrent_checks', models.PositiveIntegerField(default=10, help_text='Maximum concurrent monitoring checks')),
                ('alert_cooldown_minutes', models.PositiveIntegerField(default=5, help_text='Minutes to wait before sending duplicate alerts')),
            ],
            options={
                'verbose_name': 'Monitoring Settings',
                'verbose_name_plural': 'Monitoring Settings',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the website', max_length=200)),
                ('url', models.URLField(help_text='Full URL to monitor (e.g., https://example.com)', validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField(blank=True, help_text='Optional description of the website')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('check_interval', models.PositiveIntegerField(default=300, help_text='Check interval in seconds (default: 5 minutes)')),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Request timeout in seconds')),
                ('expected_status_code', models.PositiveIntegerField(default=200, help_text='Expected HTTP status code')),
                ('send_recovery_email', models.BooleanField(default=True, help_text='Send email when server recovers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_email', models.EmailField(help_text='Email address to send alerts to', max_length=254)),
                ('recovery_email', models.EmailField(blank=True, help_text='Email address for recovery notifications (if different from alert email)', max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the internal app', max_length=200)),
                ('app_type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend API'), ('landing', 'Landing Page'), ('admin', 'Admin Panel'), ('api', 'API Endpoint'), ('database', 'Database'), ('other', 'Other')], default='other', max_length=20)),
                ('url', models.URLField(help_text='Full URL to monitor', validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expected_status_code', models.PositiveIntegerField(default=200)),
                ('timeout', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_apps', to='monitoring.website')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('website', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('down', 'Server Down'), ('recovery', 'Server Recovery'), ('error', 'Error Alert')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.website')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=False)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('response_content', models.TextField(blank=True, help_text='First 1000 characters of response')),
                ('internal_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.internalapp')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.website')),
            ],
            options={
                'ordering': ['-check_time'],
                'indexes': [models.Index(fields=['website', 'check_time'], name='monitoring__website_583e2d_idx'), models.Index(fields=['internal_app', 'check_time'], name='monitoring__interna_69f9ab_idx')],
            },
        ),
    ]
