# Generated by Django 6.0.2 on 2026-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
