# Generated by Django 4.2.7 on 2026-03-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alertlog_is_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalapp',
            name='app_type',
            field=models.CharField(choices=[('backend', 'Backend API'), ('landing', 'Landing Page'), ('admin', 'Admin Panel'), ('database', 'Database'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
